on:
  push

name: generate_pkg_list

jobs:
  generate_pkg_list:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} - ${{ matrix.config.bioc }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macOS-12, bioc: 'devel'}
        - {os: windows-latest, bioc: 'devel'}
        - {os: ubuntu-latest, bioc: 'devel'}
        - {os: macos-14, bioc: 'devel'}
        - {os: macOS-12, bioc: '3.19'}
        - {os: windows-latest, bioc: '3.19'}
        - {os: ubuntu-latest, bioc: '3.19'}
        - {os: macos-14, bioc: '3.19'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: testenv
          environment-file: testenv.yml

      - name: List content of environment
        run: |
          conda init
          conda activate testenv
          conda list

      - name: List content of environment in format suitable for pasting into R
        if: runner.os != 'Windows'
        run: |
          conda init
          conda activate testenv
          conda list | tail -n +4 |\
          tr -s ' ' | cut -f1,2 -d' ' |\
          sed -e 's/ /==/' -e 's/^..*$/"&",/' -e '$ s/.$/)/' -e '1s/^/c(/'
