on:
  push:

name: generate_pkg_list

jobs:
  generate_pkg_list:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} - ${{ matrix.config.bioc }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macOS-12, bioc: 'devel'}
        - {os: windows-latest, bioc: 'devel'}
        - {os: ubuntu-latest, bioc: 'devel'}
        - {os: macos-14, bioc: 'devel'}
        #- {os: macOS-12, bioc: '3.19'}
        #- {os: windows-latest, bioc: '3.19'}
        #- {os: ubuntu-latest, bioc: '3.19'}
        #- {os: macos-14, bioc: '3.19'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up R and install BiocManager
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc }}

      - name: Build and test environment
        if: runner.os != 'Windows'
        run: |
          BiocManager::install(c("basilisk", "basilisk.utils"))

          deps <- c(
              "scipy==1.14.0",
              "requests==2.32.3",
              "Pillow==10.4.0",
              "h5py==3.11.0",
              "pandas==2.2.2",
              "tensorflow==2.15.0",
              "keras==2.15.0",
              "pydot==3.0.1",
              "numpy==1.26.4"
          )

          basilisk.utils::installConda()
          basilisk::setupBasiliskEnv(
            envpath = file.path(".", "orthos-basilisk-env"),
            packages = deps,
            channels = c("conda-forge", "nodefaults"))
          res <- basilisk::basiliskRun(
            env = file.path(".", "orthos-basilisk-env"),
            fun = function() {
                pd <- reticulate::import("pandas")
                pd$`__version__`
            })
          print(res)
          print(basilisk::listPackages(env = file.path(".", "orthos-basilisk-env")))
        shell: Rscript {0}

      - name: Build and test environment
        if: runner.os == 'Windows'
        run: |
          BiocManager::install(c("basilisk", "basilisk.utils"))

          deps <- c(
              "python==3.7",
              "scipy==1.7.3",
              "requests==2.32.2",
              "Pillow==9.2.0",
              "h5py==2.10.0",
              "pandas==1.3.5",
              "tensorflow==1.14.0",
              "keras==2.3.1",
              "pydot==1.4.2",
              "numpy==1.21.6"
          )

          basilisk.utils::installConda()
          basilisk::setupBasiliskEnv(
            envpath = file.path(".", "orthos-basilisk-env"),
            packages = deps,
            channels = c("conda-forge", "nodefaults"))
          res <- basilisk::basiliskRun(
            env = file.path(".", "orthos-basilisk-env"),
            fun = function() {
                pd <- reticulate::import("pandas")
                pd$`__version__`
            })
          print(res)
          print(basilisk::listPackages(env = file.path(".", "orthos-basilisk-env")))
        shell: Rscript {0}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-version: "latest"

      - name: List content of environment
        run: conda list -p ./orthos-basilisk-env

      - name: List content of environment in format suitable for pasting into R
        if: runner.os != 'Windows'
        run: |
          conda list -p ./orthos-basilisk-env | tail -n +4 |\
          tr -s ' ' | cut -f1,2 -d' ' |\
          sed -e 's/ /==/' -e 's/^..*$/"&",/' -e '$ s/.$/)/' -e '1s/^/c(/'
